"""add user_id foreign key in todos table

Revision ID: 3343f8bd1926
Revises: 751e941ab5d3
Create Date: 2025-12-28 14:30:30.529591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3343f8bd1926"
down_revision: Union[str, Sequence[str], None] = "751e941ab5d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_todos_user_id"), "todos", ["user_id"], unique=False)
    op.create_foreign_key(
        None, "todos", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "todos", type_="foreignkey")
    op.drop_index(op.f("ix_todos_user_id"), table_name="todos")
    op.drop_column("todos", "user_id")
    # ### end Alembic commands ###
